### ISSUE TITLE
Not work with Raspbian on Rpi 3

### ISSUE THREAD

**Issue by somzoli** [electronoora/webaudio-mod-player#17]
The rewrite rules not works with apache2 on Raspbian 9.2. 
If i load .mod from anywhere and later i load other scripts, then it not work; just hanging on loading....

results the following errors in second load .mod(inspect):
TypeError: undefined is not an object (evaluating 's[i].selected=false')

http://sample.domain.com:90/original_mod/mods/original_mod/humanoids.modFailed to load resource: the server responded with a status of 404 (Not Found)

duplicated path in url...

**Comment by electronoora** [comment]
Likely you'll need to adjust the server config and/or .htaccess since the example one wouldn't work as-is. Please refer to the Apache documentation:

https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html
