### ISSUE TITLE
Doesn't work if deployed under a directory

### ISSUE THREAD

**Issue by toptnc** [electronoora/webaudio-mod-player#22]
I have tried to deploy this under a directory on Ubuntu Linux (/var/www/html/modplayer) but I only get 404 errors 

"GET /js/pt.js HTTP/1.1" 404
"GET /style.css HTTP/1.1" 404 
"GET /js/ft2.js HTTP/1.1" 404
etc...

Is there an easy way to deploy this under a directory?

**Comment by electronoora** [comment]
It should work under a directory, but you'll have to customize your server config accordingly. If you're using Apache, please refer to the documentation to set up the virtual host and/or .htaccess:

https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html
